spring:
  application:
    name: flight-service
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion-vol?createDatabaseIfNotExist=true
    username: postgres
    password: kzoldick
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8080


